#%RAML 0.8
title: Pensive API
version: v1
baseUri: https://api.pensive.com/
mediaType: application/json

resourceTypes: !include resource-types.raml

/authors:
  type:
    collection:
      exampleCollection: !include examples/authors.json
      exampleItem: !include examples/author.json
      postSchema: !include schemas/author.schema

  /{authorName}:
    type:
      collection-item:
        exampleItem: !include examples/author.json

/users:
  type:
    collection:
      exampleCollection: !include examples/users.json
      exampleItem: !include examples/user.json
      postSchema: !include schemas/user.schema

  /{userId}:
    type:
      collection-item:
        exampleItem: !include examples/user.json

    /books:
      type:
        collection:
          exampleCollection: !include examples/books.json
          exampleItem: !include examples/book.json
          postSchema: !include schemas/book.schema

      /{bookName}:
        type:
          collection-item:
            exampleItem: !include examples/book.json

/books:
  type:
    collection:
      exampleCollection: !include examples/books.json
      exampleItem: !include examples/book.json
      postSchema: !include schemas/book.schema

  /{bookName}:
    type:
      collection-item:
        exampleItem: !include examples/book.json

/notes:
  type:
    collection:
      exampleCollection: !include examples/notes.json
      exampleItem: !include examples/note.json
      postSchema: !include schemas/note.schema

  /{noteId}:
    type:
      collection-item:
        exampleItem: !include examples/note.json

/comments:
  type:
    collection:
      exampleCollection: !include examples/comments.json
      exampleItem: !include examples/comment.json
      postSchema: !include schemas/comment.schema

  /{commentId}:
    type:
      collection-item:
        exampleItem: !include examples/comment.json

/paragraphs:
  type:
    collection:
      exampleCollection: !include examples/paragraphs.json
      exampleItem: !include examples/paragraph.json
      postSchema: !include schemas/paragraph.schema

  /{paragraphId}:
    type:
      collection-item:
        exampleItem: !include examples/paragraph.json